---
- hosts: all
  user: vagrant
  sudo: true
  sudo_user: root
  gather_facts: no
  tasks:
    - name: add postgresql apt repository
      apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ lucid-pgdg main' state=present

    - name:  add postgresql apt repository key
      apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
    
    - name: apt-get update
      apt: update_cache=yes

    - name: install apt packages
      apt: update-cache=yes pkg={{ item }} state=latest
      with_items:
        - git
        - postgresql-9.3
        - postgresql-contrib-9.3
        - postgresql-server-dev-9.3
        - python-dev
        - python-psycopg2
        - python-pip
        - python-setuptools

    # We shouldn't ignore_errors for this, but the latest pip has an issue on setuptools.
    - name: upgrade pip
      command: pip install --upgrade pip
      ignore_errors: true

    - name: copy requirements file
      copy: src=requirements.txt dest=/tmp/requirements.txt

    # We shouldn't ignore_errors for this, but the latest pip has an issue on setuptools.
    - name: install requirements
      pip: requirements=/tmp/requirements.txt
      ignore_errors: true

    - name: create postgresql data directory
      file: dest="/var/lib/postgresql/9.3/main" state=directory mode=0700 owner=postgres group=postgres

    - name: install postgresql configuration
      copy: src=files/postgresql.conf dest="/etc/postgresql/9.3/main/postgresql.conf" mode=0644 owner=postgres group=postgres

    - name: install postgresql client authentication
      copy: src=files/pg_hba.conf dest="/etc/postgresql/9.3/main/pg_hba.conf" mode=0600 owner=postgres group=postgres

    - name: reload postgresql
      service: name=postgresql state=reloaded
      ignore_errors: true

    - name: update postgres password
      command: sudo -u postgres psql -c "ALTER USER postgres WITH ENCRYPTED PASSWORD 'pgpass';"

    - name: create database
      postgresql_db: login_host=127.0.0.1 login_password="pgpass" name="pgdb" owner="postgres" encoding="UTF-8"

    - name: copy initial DDL script
      copy: src=files/ddl.sql dest="/tmp/ddl.sql" mode=0600 owner=postgres group=postgres

    - name: run initial DDL script
      command: sudo su - postgres psql -c "PGPASSWORD='pgpass'; psql -d pgdb -U postgres < /tmp/ddl.sql"
